project-magnet/magnet

src/main/java/com/example/magnet/member/entity/Member.java

- entity 생성
- 주소는 Embedded class로 생성 
- 회원 권한은 Enum 타입으로 생성했지만 추후 변동 가능.

edit entity

---

build.gradle
src/main/java/com/example/magnet/global/auth/jwt/JwtTokenizer.java
src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/member/controller/LoginController.java
src/main/java/com/example/magnet/member/controller/MemberController.java
src/main/java/com/example/magnet/member/dto/AddressDto.java
src/main/java/com/example/magnet/member/dto/MemberDto.java
src/main/java/com/example/magnet/member/dto/MemberResponseDto.java
src/main/java/com/example/magnet/member/entity/Member.java
src/main/java/com/example/magnet/member/repository/MemberRepository.java
src/main/java/com/example/magnet/member/service/MemberService.java
src/main/java/com/example/magnet/mentee/entity/Mentee.java
src/main/java/com/example/magnet/mentor/entity/Mentor.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java
src/main/java/com/example/magnet/review/entity/Review.java
src/test/java/com/example/magnet/global/auth/jwt/JwtTokenizerTest.java

- jwtTokenizer 구현 
- jwt signature를 이용한 생성 및 검증 기능 구현 
- 생성, 검증 테스트 코드 구현

[feat]jwt 생성 및 검증 기능 구현 

---

src/main/java/com/example/magnet/MagnetApplication.java
src/main/java/com/example/magnet/global/audit/Base.java
src/main/java/com/example/magnet/global/audit/TimeEntity.java

- 생성시간, 수정시간 클래스 TimeEntity 
- 생정자, 수정자 클래스 Base
- main 클래스에서 jwt에 담긴 사용자 정보를 전달하는 것은 jwt 구현을 모두 마친 후 진행 예정

[feat]add auditing class

---

src/main/java/com/example/magnet/global/exception/ExceptionCode.java
src/main/java/com/example/magnet/member/dto/MemberResponseDto.java
src/main/java/com/example/magnet/member/dto/SignupResponseDto.java
src/main/java/com/example/magnet/member/entity/Member.java
src/main/java/com/example/magnet/member/mapper/MemberMapper.java
src/main/java/com/example/magnet/member/service/MemberService.java
src/test/java/com/example/magnet/member/service/MemberServiceTest.java

- MemberBuilder 클래스 사용
-  toBuilder 메소드를 통해 매개변수로 넘어온 인스턴스 변수를 직접 사용하고 수정해서 데이터베이스에 반영했습니다. 
- 또 다른 빌더를 생성해 기능이 중복되고 메모리가 낭비되는 상황을 해결했습니다.

[refactor]회원가입 기능 빌더 수정

---

build.gradle
src/main/java/com/example/magnet/global/auth/filter/JwtAuthenticationFilter.java
src/main/java/com/example/magnet/global/auth/handler/LoginAuthenticationFailureHandler.java
src/main/java/com/example/magnet/global/auth/handler/LoginAuthenticationSuccessHandler.java
src/main/java/com/example/magnet/global/config/SecurityConfig.java

- LoginAuthenticationSuccessHandler 구현 
- LoginAuthenticationFailureHandler 구현 : 콘솔확인만 진행

[feat]login handler 구현

---

Dockerfile
build.gradle
docker-compose-dev.yml
src/main/java/com/example/magnet/global/auth/details/MemberDetailService.java
src/main/java/com/example/magnet/global/auth/dto/LoginDto.java
src/main/java/com/example/magnet/global/auth/filter/JwtAuthenticationFilter.java
src/main/java/com/example/magnet/global/auth/filter/JwtVerificationFilter.java
src/main/java/com/example/magnet/global/auth/handler/LoginAuthenticationFailureHandler.java
src/main/java/com/example/magnet/global/auth/handler/MemberAccessDeniedHandler.java
src/main/java/com/example/magnet/global/auth/handler/MemberAuthenticationEntryPoint.java
src/main/java/com/example/magnet/global/auth/handler/OAuth2MemberSuccessHandler.java
src/main/java/com/example/magnet/global/auth/jwt/JwtTokenizer.java
src/main/java/com/example/magnet/global/auth/oauth/CustomOAuth2UserService.java
src/main/java/com/example/magnet/global/auth/oauth/MyAuthenticationFailureHandler.java
src/main/java/com/example/magnet/global/auth/oauth/MyAuthenticationSuccessHandler.java
src/main/java/com/example/magnet/global/auth/oauth/OAuth2Attribute.java
src/main/java/com/example/magnet/global/auth/utils/ErrorResponder.java
src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/global/response/ErrorResponse.java
src/main/java/com/example/magnet/member/controller/MemberController.java
src/main/java/com/example/magnet/member/entity/Member.java
src/main/resources/application-oauth.yml

- 구글 로그인 로컬 테스트 완료. accessToken 발급 확인. 
- 테스트 코드 미 작성 
- 로그아웃 기능 구현 진행 예정 
- 로그아웃 기능 구현으로 인한 redis 적용 준비 
- oauth2 로그인 시 최초 1회 로그인에 한하여 DB에 사용자 정보 저장 기능 재검토 필요  
- docker 환경

[feat-ongoing] OAuth2.0 로그인 구현 

---

Dockerfile
docker-compose-dev.yml
src/main/java/com/example/magnet/global/auth/handler/OAuth2MemberSuccessHandler.java
src/main/java/com/example/magnet/global/auth/jwt/JwtTokenizer.java
src/main/java/com/example/magnet/global/auth/oauth/CustomOAuth2UserService.java
src/main/java/com/example/magnet/global/auth/oauth/GeneratedToken.java
src/main/java/com/example/magnet/global/auth/oauth/OAuth2Attribute.java
src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/member/entity/Member.java
src/main/java/com/example/magnet/member/service/MemberService.java
src/main/resources/application-oauth.yml

- successHandler의 memberService DI 이슈로 인해 다른 방법 구현 중

[feat - ongoing] oauth2 로그인 구현

---

src/main/java/com/example/magnet/member/controller/LoginController.java
src/main/java/com/example/magnet/member/controller/MemberController.java
src/main/java/com/example/magnet/member/entity/Member.java
src/main/java/com/example/magnet/member/service/MemberService.java
src/main/java/com/example/magnet/mentee/entity/Mentee.java
src/main/java/com/example/magnet/mentor/entity/Mentor.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java

- 멘토, 멘토링의 연관관계 주인은 멘토입니다. 멘토만이 수정, 등록이 가능합니다. 
- 멘티, 멘토링의 연관관계 주인은 멘티입니다. 멘티만이 수정, 등록이 가능합니다. 
- 멘토링은 조회만 가능합니다.

[fix]멘토링 연관관계 수정

---

docs/src/App.tsx
docs/src/component/common/BottomMenu.tsx
docs/src/component/common/Footer.tsx
docs/src/component/common/Header.tsx
docs/src/component/payment/PaymentButton.tsx
docs/src/component/payment/PaymentInput.tsx
docs/src/component/payment/PaymentPopup.tsx
docs/src/pages/HomePage.tsx
docs/src/pages/MentorPage.tsx
docs/src/pages/PaymentCompletedPage.tsx
docs/src/styles/tailwind.css

멘토링 신청 시, 
팝업으로 나의 정보와 일정을 선택한 이후에 결제를 하게끔 하는 컴포넌트 구현함.
구현 도중에 불필요한 가로스크롤을 인지했으며, 고침
헤더및 푸터 반응형 디자인 작업을 함.

Payment popup

---

docs/src/component/auth/LoginForm.tsx
docs/src/pages/LoginEmailPage.tsx
docs/src/pages/LoginPage.tsx
docs/src/pages/MentorListPage.tsx
docs/src/pages/PaymentCompletedPage.tsx
docs/src/pages/SignupPage.tsx

- 결제완료 페이지 구조 구현
- 모든페이지 w-screen 변경 -> w-full (안정화)

Payment completed page

---

docs/src/App.tsx
docs/src/component/MentorCard.tsx
docs/src/component/auth/LoginButton.tsx
docs/src/component/payment/PaymentButton.tsx
docs/src/component/user/Schedulebox.tsx
docs/src/component/user/ScheduleboxV2.tsx
docs/src/component/user/UserInfoBox.tsx
docs/src/pages/MentorListPage.tsx
docs/src/pages/MentorPage.tsx
docs/src/pages/PaymentCompletedPage.tsx
docs/src/pages/UserPage.tsx
docs/src/styles/tailwind.css

- 유저페이지 구조를 구현함.
- 스케줄박스 컴포넌트 2개의 스타일로 구현함.
- 유저정보박스 컴포넌트 구조를 구현함
- 전역 스타일을 구현하고 적용함

User page 구조 구현

---

src/main/java/com/example/magnet/MagnetApplication.java
src/main/java/com/example/magnet/member/controller/MemberController.java
src/main/java/com/example/magnet/member/dto/MemberDto.java
src/main/java/com/example/magnet/member/dto/MemberResponseDto.java
src/main/java/com/example/magnet/member/entity/Member.java
src/main/java/com/example/magnet/member/mapper/MemberMapper.java
src/main/java/com/example/magnet/member/repository/MemberRepository.java
src/main/java/com/example/magnet/member/service/MemberService.java
src/main/java/com/example/magnet/mentee/entity/Mentee.java
src/main/java/com/example/magnet/mentor/entity/Mentor.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java
src/test/java/com/example/magnet/member/service/MemberServiceTest.java

- 회원 조회는 테스트 코드 작성이 완료되었습니다. 
- 회원수정은 아직 진행중입니다.

[feat] 회원조회, 회원 수정 기능 구현 

---

src/main/java/com/example/magnet/global/config/QueryDslConfig.java
src/main/java/com/example/magnet/global/exception/ExceptionCode.java
src/main/java/com/example/magnet/member/controller/MemberController.java
src/main/java/com/example/magnet/mentor/controller/MentorController.java
src/main/java/com/example/magnet/mentor/dto/MentorResponseDto.java
src/main/java/com/example/magnet/mentor/repository/MentorCustomRepository.java
src/main/java/com/example/magnet/mentor/repository/MentorRepositoryImpl.java
src/main/java/com/example/magnet/mentor/service/MentorService.java

[config]QueryDSL config 추가

---

src/main/java/com/example/magnet/MagnetApplication.java
src/main/java/com/example/magnet/global/audit/TimeEntity.java
src/main/java/com/example/magnet/member/entity/Member.java
src/main/java/com/example/magnet/member/entity/Role.java
src/main/java/com/example/magnet/member/service/MemberService.java
src/main/java/com/example/magnet/mentee/repository/MenteeRepository.java
src/main/java/com/example/magnet/mentor/controller/MentorController.java
src/main/java/com/example/magnet/mentor/dto/MentorResponseDto.java
src/main/java/com/example/magnet/mentor/mapper/MentorMapper.java
src/main/java/com/example/magnet/mentor/repository/MentorCustomRepository.java
src/main/java/com/example/magnet/mentor/repository/MentorRepository.java
src/main/java/com/example/magnet/mentor/repository/MentorRepositoryImpl.java
src/main/java/com/example/magnet/mentor/service/MentorService.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java
src/main/java/com/example/magnet/mentoring/repository/MentoringRepository.java
src/test/java/com/example/magnet/member/service/MemberServiceTest.java
src/test/java/com/example/magnet/mentor/service/MentorServiceTest.java

- mapper 클래스 component 제거 후 static 메소드로 변경 > 인스턴스 생성 없이도 사용 가능하게 변경 
- role 권한 테이블 보류 > 현재 값 타입 컬렉션으로 진행중

[hotfix] soft delete 삭제 시간 변경감지 기능 추가

---

docs/src/component/user/MentorRegistPopup.tsx
docs/src/component/user/ScheduleboxV2.tsx
docs/src/pages/UserPage.tsx
docs/src/styles/tailwind.css

Mentor registration

---

src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/mentor/controller/MentorController.java
src/main/java/com/example/magnet/mentor/dto/MentorSearchResponseDto.java
src/main/java/com/example/magnet/mentor/dto/MentorSearchResponseDtoV2.java
src/main/java/com/example/magnet/mentor/entity/Mentor.java
src/main/java/com/example/magnet/mentor/mapper/MentorMapper.java
src/main/java/com/example/magnet/mentor/repository/MentorCustomRepository.java
src/main/java/com/example/magnet/mentor/repository/MentorRepository.java
src/main/java/com/example/magnet/mentor/repository/MentorRepositoryImpl.java
src/main/java/com/example/magnet/mentor/service/MentorService.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java
src/test/java/com/example/magnet/mentor/service/MentorServiceTest.java
src/test/resources/application.yml

- QueryDSL을 이용한 페이징 구현 
- dto 수정 중. 현재 fetch join으로 인한 테스트 fail.

[feat] 멘토 목록 조회 기능 구현 

---

docs/src/component/auth/LoginForm.tsx
docs/src/component/common/Header.tsx
docs/src/component/user/MentorRegistPopup.tsx
docs/src/pages/LoginPage.tsx
docs/src/pages/UserPage.tsx

[feat] Conditional rendering

---

src/main/java/com/example/magnet/member/service/MemberService.java
src/main/java/com/example/magnet/mentor/controller/MentorController.java
src/main/java/com/example/magnet/mentor/service/MentorService.java
src/main/java/com/example/magnet/mentoring/controller/MentoringController.java
src/main/java/com/example/magnet/mentoring/dto/MentoringPostDto.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java
src/main/java/com/example/magnet/mentoring/service/MentoringService.java
src/test/java/com/example/magnet/member/service/MemberServiceTest.java
src/test/java/com/example/magnet/mentor/service/MentorServiceTest.java
src/test/resources/application.yml

- 영속성 전이 특성으로 인해 findMentor.getMentoringList.clear()과정을 삭제했습니다.

[[test] 멘토 삭제 테스트 코드 구현

---

src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/member/entity/Member.java
src/main/java/com/example/magnet/member/service/MemberService.java
src/main/java/com/example/magnet/mentee/entity/Mentee.java
src/main/java/com/example/magnet/mentor/dto/MentorSearchResponseDtoV2.java
src/main/java/com/example/magnet/mentor/entity/Mentor.java
src/main/java/com/example/magnet/mentor/mapper/MentorMapper.java
src/main/java/com/example/magnet/mentor/service/MentorService.java
src/main/java/com/example/magnet/mentoring/controller/MentoringController.java
src/main/java/com/example/magnet/mentoring/dto/MentoringPostDto.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java
src/main/java/com/example/magnet/mentoring/mapper/MentoringMapper.java
src/main/java/com/example/magnet/mentoring/service/MentoringService.java
src/test/java/com/example/magnet/mentor/service/MentorServiceTest.java
src/test/java/com/example/magnet/mentoring/service/MentoringServiceTest.java

- test 방법 변경 > mock은 추후 고도화에 적용

[feat/test] 멘토링 등록 기능 구현

---

.gitignore
src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/global/config/WebSecurityConfig.java
src/main/java/com/example/magnet/mentoring/controller/MentoringController.java
src/main/java/com/example/magnet/mentoring/dto/MentoringResponseDto.java
src/main/java/com/example/magnet/mentoring/repository/GetMentoringRepository.java
src/main/java/com/example/magnet/mentoring/repository/GetMentoringRepositoryImpl.java
src/main/java/com/example/magnet/mentoring/service/MentoringService.java

- WebMvcConfigurer의 구현체인 WebSecurityConfig 를 통해 addCorsMappings()메소드를 작성했습니다. 
- Access-Control-Allow-Origin 를 헤더에 노출시켜서 front-end의 preflight 요구조건을 충족시켰습니다.

[hotfix] CORS error 해결

---

docs/src/component/MentorCard.tsx
docs/src/component/auth/LoginButton.tsx
docs/src/component/auth/LoginForm.tsx
docs/src/component/auth/SignupForm.tsx
docs/src/component/user/MentorRegistPopup.tsx
docs/src/pages/HomePage.tsx
docs/src/pages/MentorListPage.tsx
docs/src/styles/tailwind.css
docs/tailwind.config.js

[design] Design token

---

src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/mentoring/controller/MentoringController.java
src/main/java/com/example/magnet/mentoring/mapper/MentoringMapper.java
src/main/java/com/example/magnet/mentoring/repository/GetMentoringRepository.java
src/main/java/com/example/magnet/mentoring/repository/GetMentoringRepositoryImpl.java
src/main/java/com/example/magnet/mentoring/service/MentoringService.java

- querydsl 이용해 mentoring 단건 조회기능을 구현했습니다. mentor 테이블은 fetch join으로 호출했습니다.

[feat]getMentori m 단건 조회기능 구현

---

src/main/java/com/example/magnet/global/auth/utils/CustomAuthorityUtils.java
src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/mentor/controller/MentorController.java
src/main/java/com/example/magnet/mentor/service/MentorService.java
src/main/java/com/example/magnet/mentoring/controller/MentoringController.java
src/main/java/com/example/magnet/mentoring/dto/mentoringListPagingDto.java
src/main/java/com/example/magnet/mentoring/repository/GetMentoringRepository.java
src/main/java/com/example/magnet/mentoring/repository/GetMentoringRepositoryImpl.java
src/main/java/com/example/magnet/mentoring/service/MentoringService.java
src/test/java/com/example/magnet/mentor/service/MentorServiceTest.java

- QueryDsl을 이용한 페이지네이션 구현 
- 조회한 mentorId로 멘토 단건 조회 가능합니다.

[feat] mentoring list 조회기능 구현

---

src/main/java/com/example/magnet/global/auth/details/MemberDetailService.java
src/main/java/com/example/magnet/global/config/TossPaymentConfig.java
src/main/java/com/example/magnet/global/exception/ExceptionCode.java
src/main/java/com/example/magnet/global/response/SliceInfo.java
src/main/java/com/example/magnet/global/response/SliceResponseDto.java
src/main/java/com/example/magnet/member/dto/MemberDto.java
src/main/java/com/example/magnet/member/dto/MemberPostDto.java
src/main/java/com/example/magnet/member/entity/Member.java
src/main/java/com/example/magnet/member/service/MemberService.java
src/main/java/com/example/magnet/payment/controller/PaymentController.java
src/main/java/com/example/magnet/payment/dto/ChargingHistoryDto.java
src/main/java/com/example/magnet/payment/dto/PaymentFailDto.java
src/main/java/com/example/magnet/payment/dto/PaymentResponseDto.java
src/main/java/com/example/magnet/payment/dto/PaymentSuccessCardDto.java
src/main/java/com/example/magnet/payment/dto/PaymentSuccessDto.java
src/main/java/com/example/magnet/payment/mapper/PaymentMapper.java
src/main/java/com/example/magnet/payment/service/PaymentService.java
src/test/java/com/example/magnet/member/entity/MemberTest.java
src/test/java/com/example/magnet/payment/controller/PaymentControllerTest.java

[feat/test - ongoing] 토스 결제기능 테스트

---

src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/member/dto/MemberResponseDto.java
src/main/java/com/example/magnet/member/mapper/MemberMapper.java
src/main/java/com/example/magnet/member/service/MemberService.java
src/main/java/com/example/magnet/mentee/controller/MenteeController.java
src/main/java/com/example/magnet/mentee/dto/MenteePostDto.java
src/main/java/com/example/magnet/mentoring/dto/mentoringListPagingDto.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java
src/main/java/com/example/magnet/mentoring/repository/GetMentoringRepositoryImpl.java
src/main/java/com/example/magnet/payment/controller/PaymentController.java
src/main/java/com/example/magnet/payment/controller/WidgetController.java
src/main/java/com/example/magnet/payment/service/PaymentService.java

- 토스페이먼츠 결제 요청 및 결제 승인 api 구현 테스트 완료
- 멘토링 리스트 조회 시 mentor 정보 추가 노출하도록 코드 리팩토링

[feat/refactor] toss, mentoring

---

docs/package-lock.json
docs/package.json
docs/src/Router.tsx
docs/src/api/mentoring.ts
docs/src/component/MentorCard.tsx
docs/src/component/payment/PaymentButton.tsx
docs/src/component/payment/PaymentPopup.tsx
docs/src/component/payment/TossPayment.tsx
docs/src/pages/MentorListPage.tsx
docs/src/pages/PaymentCompletedPage.tsx
docs/src/pages/PaymentFailedPage.tsx
docs/src/utils/payments/openTossPayments.ts

[feat] Tosspayment client

---

docs/.prettierrc
docs/package-lock.json
docs/package.json
docs/src/component/user/UserInfoBox.tsx
docs/src/pages/UserPage.tsx
docs/src/styles/tailwind.css
docs/src/utils/auth/removeToken.ts

프리티어 테일윈드 플러그인 설정
토큰 삭제기능
유저페이지 구조 변경

Serverless logout

---

docs/src/api/mentoring.ts
docs/src/component/MentorCard.tsx
docs/src/component/common/Header.tsx
docs/src/component/common/LoadingContainer.tsx
docs/src/component/payment/PaymentButton.tsx
docs/src/component/payment/PaymentInput.tsx
docs/src/component/payment/PaymentPopup.tsx
docs/src/pages/MentorListPage.tsx
docs/src/pages/UserPage.tsx

[feat] Apply data paymentpopup

---

src/main/java/com/example/magnet/member/dto/MemberResponseDto.java
src/main/java/com/example/magnet/member/mapper/MemberMapper.java
src/main/java/com/example/magnet/mentee/controller/MenteeController.java
src/main/java/com/example/magnet/mentee/dto/MenteePostDto.java
src/main/java/com/example/magnet/mentee/dto/MenteeResponseDto.java
src/main/java/com/example/magnet/mentee/entity/Mentee.java
src/main/java/com/example/magnet/mentee/mapper/MenteeMapper.java
src/main/java/com/example/magnet/mentee/service/MenteeService.java
src/main/java/com/example/magnet/mentor/dto/MentorPostDto.java
src/main/java/com/example/magnet/mentor/entity/Mentor.java
src/main/java/com/example/magnet/mentor/mapper/MentorMapper.java
src/main/java/com/example/magnet/mentor/service/MentorService.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java
src/main/java/com/example/magnet/payment/controller/PaymentController.java
src/main/java/com/example/magnet/payment/dto/PaymentDto.java
src/main/java/com/example/magnet/payment/mapper/PaymentMapper.java
src/main/java/com/example/magnet/payment/repository/PaymentRepository.java
src/main/java/com/example/magnet/payment/service/PaymentService.java
src/test/java/com/example/magnet/member/service/MemberServiceTest.java

-멘티 등록기능 구현
- -결제 승인 api 이후 발급된 paymentKey를 통해 결제가 완료됐는지 검증하고 멘토링과 관련된 멘티 정보를 전달받아 DB에 저장합니다. 
- 회원 조회 리팩토링 
- - 회원테이블과 연관관계에 있는 모든 테이블의 데이터를 묶어서 조회합니다. 
- - 현재는 JPA를 이용해 조회합니다. 조회 성능을 위해 리팩토링이 필요할 수 있습니다.

[feat/refactor]mentee 등록 기능 및 getMember 리팩토링

---

src/main/java/com/example/magnet/member/entity/Member.java
src/main/java/com/example/magnet/member/repository/MemberCustomRepository.java
src/main/java/com/example/magnet/member/repository/MemberCustomRepositoryImpl.java
src/main/java/com/example/magnet/member/repository/MemberRepository.java
src/main/java/com/example/magnet/member/service/MemberService.java
src/main/java/com/example/magnet/mentee/dto/MenteePostDto.java
src/main/java/com/example/magnet/mentee/mapper/MenteeMapper.java
src/main/java/com/example/magnet/mentee/service/MenteeService.java
src/main/java/com/example/magnet/mentor/entity/Mentor.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java
src/main/java/com/example/magnet/payment/controller/PaymentController.java
src/main/java/com/example/magnet/payment/service/PaymentService.java
src/test/java/com/example/magnet/member/service/MemberServiceTest.java

- 회원 정보 조회 시 연관관계 범위 보류  및 리팩토링 필요.
- fetch join 관련 문제 발생 
-  BusinessLogicException 발생. 쿼리 재확인 필요

[refactor]getMember Querydsl 적용 보류

---

src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/global/exception/ExceptionCode.java
src/main/java/com/example/magnet/member/dto/MemberResponseDto.java
src/main/java/com/example/magnet/member/mapper/MemberMapper.java
src/main/java/com/example/magnet/mentee/dto/MenteePostDto.java
src/main/java/com/example/magnet/mentee/dto/MenteeResponseDto.java
src/main/java/com/example/magnet/mentee/dto/MenteeResponseDtoV2.java
src/main/java/com/example/magnet/mentee/entity/Mentee.java
src/main/java/com/example/magnet/mentee/mapper/MenteeMapper.java
src/main/java/com/example/magnet/mentee/service/MenteeService.java
src/main/java/com/example/magnet/mentor/dto/MentorPostDto.java
src/main/java/com/example/magnet/mentor/entity/Mentor.java
src/main/java/com/example/magnet/mentor/service/MentorService.java
src/main/java/com/example/magnet/payment/dto/PaymentDto.java
src/main/java/com/example/magnet/payment/dto/PaymentResponseDto.java
src/main/java/com/example/magnet/payment/entity/Payment.java
src/main/java/com/example/magnet/payment/repository/PaymentRepository.java
src/main/java/com/example/magnet/payment/service/PaymentService.java

- 멘티 신청 시 email 추가 
- 멘티 등록 시 권한 부여 기능 추가 
- 중복 결제 검증 로직 구현 
- payment에 mentoringId를 추가해서 구분 시 사용.

[feat/refactor]멘티 등록기능 수정

---

docs/src/api/mentee.ts
docs/src/api/mentoring.ts
docs/src/api/payments.ts
docs/src/component/payment/PaymentButton.tsx
docs/src/component/payment/PaymentInput.tsx
docs/src/component/payment/PaymentPopup.tsx
docs/src/hooks/useAddPath.ts
docs/src/pages/PaymentCompletedPage.tsx
docs/src/store/MenteeStore.ts
docs/src/store/MentoringStore.ts
docs/src/utils/payments/openTossPayments.ts

[feata] Mentee api

---

docs/src/component/common/Header.tsx
docs/src/pages/HomePage.tsx
docs/src/pages/MentorListPage.tsx
docs/src/styles/tailwind.css
docs/tailwind.config.js

[design] Mainpage

---

docs/src/App.tsx
docs/src/component/auth/LoginButton.tsx
docs/src/component/auth/LoginForm.tsx
docs/src/component/auth/LoginPopup.tsx
docs/src/component/common/Header.tsx
docs/src/pages/HomePage.tsx
docs/src/pages/MentorListPage.tsx
docs/src/store/LoginPopupStore.ts
docs/tailwind.config.js

Login popup

---

Dockerfile
build.gradle
src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/global/config/WebSecurityConfig.java

- dockerfile 설정 구성. 
- cors origin 설정 변경.

[hotfix] docker설정 및 cors문제 해결

---

docs/src/component/auth/LoginForm.tsx
docs/src/component/auth/LoginPopup.tsx
docs/src/component/auth/SignupForm.tsx
docs/src/component/common/WarningMessage.tsx
docs/src/pages/HomePage.tsx
docs/src/pages/SignupPage.tsx
docs/tailwind.config.js

[refactor] Refactoring master

---

docs/src/component/auth/LoginPopup.tsx
docs/src/component/auth/SignupForm.tsx
docs/src/component/common/LogoMagnet.tsx
docs/src/pages/SignupPage.tsx
docs/tailwind.config.js

[design] Sighup layout

---

docs/src/api/member.ts
docs/src/component/common/Header.tsx
docs/src/store/MemberStore.ts

[feat] Member store

---

docs/src/component/user/MentorRegistPopup.tsx

[refactor] 전역변수 연결 및 디자인 개선

---

docs/src/component/MentorCard.tsx
docs/src/component/auth/LoginForm.tsx
docs/src/component/auth/LoginPopup.tsx
docs/src/component/auth/SignupForm.tsx
docs/src/component/common/BottomMenu.tsx
docs/src/component/common/Header.tsx
docs/src/component/payment/PaymentButton.tsx
docs/src/component/payment/PaymentPopup.tsx
docs/src/component/user/MentorRegistPopup.tsx
docs/src/component/user/MentorRegistSection.tsx
docs/src/component/user/UserInfoSection.tsx
docs/src/pages/CreateMentoringPage.tsx
docs/src/pages/MentorListPage.tsx
docs/src/styles/tailwind.css
docs/tailwind.config.js

Refactor payment popup

---

src/main/java/com/example/magnet/global/auth/details/MemberDetailService.java
src/main/java/com/example/magnet/global/auth/filter/JwtAuthenticationFilter.java
src/main/java/com/example/magnet/global/auth/filter/JwtVerificationFilter.java
src/main/java/com/example/magnet/global/config/SecurityConfig.java
src/main/java/com/example/magnet/global/config/WebSecurityConfig.java
src/main/java/com/example/magnet/member/controller/MemberController.java
src/main/java/com/example/magnet/mentoring/controller/MentoringController.java
src/main/java/com/example/magnet/mentoring/entity/Mentoring.java
src/main/java/com/example/magnet/payment/controller/PaymentController.java

- pageable 적용으로 mentoring list 문제 해결. default size=20으로 설정되어있습니다. 추후 100으로 변경 예정입니다. 
- member/get 경로의 500 error 해결중입니다.

Feat mentoring

---

client/src/component/auth/LoginPopup.tsx
client/src/pages/HomePage.tsx
client/src/pages/PaymentFailedPage.tsx
client/src/styles/tailwind.css
client/tailwind.config.js

[feat] Paymentfailepage
